"use client"

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Header } from "@/components/shared/Header";
import { Footer } from "@/components/shared/Footer";
import { AppDownload } from '@/components/shared/AppDownload';
=======
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "../lib/queryClient";
>>>>>>> user-orders

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Organic Store - Fresh & Healthy Products",
  description: "Your one-stop shop for organic products, fresh vegetables, fruits, and more.",
};
=======
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
>>>>>>> user-orders

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <AppDownload />
          <Footer />
        </div>
=======
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
>>>>>>> user-orders
      </body>
    </html>
  );
}
